# Generated by Django 5.0.7 on 2024-08-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LUX", "Luxury"),
                            ("PICKUP", "Pickup"),
                            ("NORMAL", "Normal"),
                            ("OTHER", "Other"),
                        ],
                        default="NORMAL",
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
            },
        ),
    ]
